before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - windows
  - linux
  - darwin 
archive:
  format: tar.gz
  format_overrides:
  - goos: windows
    format: zip
  name_template: "{{ .ProjectName  }}-{{ .Os  }}-{{ .Arch  }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brew:
  github:
    owner: nholuongut
    name: homebrew-nholuongut
  folder: Formula
  description: "Validate your Kubernetes configurations"
  homepage: "https://github.com/nholuongut/kubeval"
  test: |
    system "#{bin}/kubeval --version"
scoop:
  bucket:
    owner: nholuongut
    name: scoop-nholuongut
  description: "Validate your Kubernetes configurations"
  homepage: "https://github.com/nholuongut/kubeval"
